### ISSUE TITLE
Don't install modules by default

### ISSUE THREAD

**Issue by ninjamar** [The-Cloud-Dev/scratch2py#16]
Installing modules by default is bad because the user may want to install them personally using venv or something

**Comment by The-Cloud-Dev** [comment]
The modules were never installed by default, but many users didn't install them and recommended I made an update and added 'install_requires' in setup.py

**Comment by ninjamar** [comment]
I meant the __init__.py file

**Comment by ninjamar** [comment]
> Oh, you mean when the modules are not detected they are manually installed?

yes
