### ISSUE TITLE
Encrypt decimal number.

### ISSUE THREAD

**Issue by ajsya** [The-Cloud-Dev/scratch2py#19]
I'm trying to encrypt a number but I'm getting this error:

`Traceback (most recent call last):
  File "/Users/Me/Desktop/Coding_Files/Python Projects/WeatherApp/app2.py", line 58, in <module>
    project.setCloudVar("request", s2py.encode(weather[y]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scratch2py/__init__.py", line 85, in encode
    text = text.lower()
AttributeError: 'float' object has no attribute 'lower'`

I understand this is because I'm trying to encrypt a decimal number known as a float but I'm not sure what to do about it or if this can be fixed in scratch2py.

**Comment by The-Cloud-Dev** [comment]
Since this caused by text.lower(), I can only remove it by making ScratchEncoder case sensitive, which would take some time, but all I have to do is change the chars list and remove text.lower() in the encoder. Will update when done.

**Comment by The-Cloud-Dev** [comment]
Fixed and added suport for uppercase. Check the project for updated version: https://scratch.mit.edu/projects/546443308/

**Comment by ajsya** [comment]
Ok, but now I'm getting another error:

`Traceback (most recent call last):
  File "/Users/Me/Desktop/Coding_Files/Python Projects/WeatherApp/app3.py", line 59, in <module>
    project.setCloudVar(variables[y], s2py.encode(weather[y]))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scratch2py/__init__.py", line 87, in encode
    length = int(len(text))
TypeError: object of type 'float' has no len()`

**Comment by The-Cloud-Dev** [comment]
Why don't you try wraping your text in str()? See if that works... I tried to encode 1.1 and it worked

**Comment by The-Cloud-Dev** [comment]
![image](https://user-images.githubusercontent.com/85949157/140840600-65d511cb-4eee-44b0-ae2b-6e1e7fe31c1b.png)
As you can see, adding str() seems to work. Tell me if that works for you.

**Comment by ajsya** [comment]
I found out what was going wrong, in the previous version my code was looking for an Attribute Error to know to make the decimal a string, but now the error comes across as a Type Error for some reason. So in a way you were right. Once I share the project I'll show you the code and it'll make a lot more sense.
