### ISSUE TITLE
The vercel app has an 404 error

### ISSUE THREAD

**Issue by FuchsCrafter** [The-Cloud-Dev/scratch2py#21]
Nothing much to say here

> Oh and @themysticsavages the vercel app is 404 rn

_Originally posted by @FuchsCrafter in https://github.com/The-Cloud-Dev/scratch2py/issues/9#issuecomment-1001005669_

**Comment by The-Cloud-Dev** [comment]
I created the vercel app to make a HTML webpage with doccumentation, but got too lazy so there's nothing there (yet?).

**Comment by FuchsCrafter** [comment]
Just like me :smile:
