### ISSUE TITLE
Problematic connections to clouddata.turbowarp.org

### ISSUE THREAD

**Issue by GarboMuffin** [The-Cloud-Dev/scratch2py#22]
Recently there's been a lot of messages in clouddata.turbowarp.org's logs about connections being closed with `Error: Unknown message method: get (code 4000)`. I don't know exactly why a bunch of those have started appearing, but a GitHub code search has led me to this repository.

https://github.com/The-Cloud-Dev/scratch2py/blob/50fe60cad38c3955d6a3bf68138a50721429f41e/scratch2py/__init__.py#L791-L804

`get` is not a valid method. Connections that send that to clouddata.turbowarp.org will be closed because the server doesn't know how to handle it. The proper way to get a variable is to open a single connection and listen to the messages that the server sends you to record the most recent value on your own. That way you can look up the most recent value whenever you want without asking the server. If your current code works, then that's only a lucky coincidence because of other bugs in your code. There is a high probability that it will break in the future.

I suspect that this broken logic in this library may be responsible for nearly 400,000 (four hundred thousand) unnecessary short lived connections to clouddata.turbowarp.org per day. I do not appreciate this level of spam and may consider outright blocking users that continue to make these connections, which may or may not affect you and/or users of this library.

**Comment by The-Cloud-Dev** [comment]
Sorry for the trouble, all connections to wss://clouddata.turbowarp.org have no been removed.

**Comment by ajskateboarder** [comment]
Any updates on this issue?

**Comment by GarboMuffin** [comment]
To be clear, there is nothing wrong with this library containing a feature to connect to clouddata.turbowarp.org. It just needs to do so in a way that follows the cloud variable protocol and doesn't cause excessive connections. Many other libraries have figured this out. I hope that this library can too.
