### ISSUE TITLE
Permission issues with the log module on Linux

### ISSUE THREAD

**Issue by FuchsCrafter** [The-Cloud-Dev/scratch2py#23]
So recently, there is an issue with the log output, that denies the programm to access the logfile if executed as a non-administrative user. Im still searching for a solution on my own and will inform you if I found a solution. For now, I can just run the script as a root.
I understand that this bug is maybe not caused by Scratch2Py and may not affect Windows or MacOS.

**Comment by The-Cloud-Dev** [comment]
Did you find a solution yet?

**Comment by FuchsCrafter** [comment]
> Did you find a solution yet?

Only kind of: 
I downloaded the library, imported it as a folder and removed the logging module, and it works fine. But I don't think that this will be the solution. I also think that this is **not** caused by Scratch2Py.

**Comment by FuchsCrafter** [comment]
I'll try to fix this today

**Comment by FuchsCrafter** [comment]
Seems like that the issue is fixed (Maybe due an log module update?)
