### ISSUE TITLE
Add users PFF codes for lists - AybarsA123

### ISSUE THREAD

**Issue by AybarsA123** [The-Cloud-Dev/scratch2py#25]
You can add PFF function in Scratch2py

**Comment by The-Cloud-Dev** [comment]
What do you mean by a PFF function?

**Comment by FuchsCrafter** [comment]
Do you mean PFP (Profile Picture, also avatar)?
This would be easy to implement because you have to 
1. Get the user's ID from the Api (for example: `55941874`)
2. Do `https://uploads.scratch.mit.edu/get_image/user/{}_{}x{}.png.format(id, x, y)`
Done!

**Comment by themysticsavages** [comment]
@FuchsCrafter i made a function to do something like this in [`scratchhh`](https://github.com/themysticsavages/scratchhh).
```py
def getUserAv(user:str, url=False, file='userav.gif'):
    if url == False:
        uid = json.loads(requests.get('{}users/ajskateboarder/'.format(Scratch.API_URL)).text)['id']
        r = requests.get('{}get_image/user/{}_60x60.png'.format(Scratch.CDN_URL, uid), stream=True)
        if r.status_code == 200:
            with open(file, 'wb') as f:
                for chunk in r.iter_content(1024):
                    f.write(chunk)
    elif url == True:
        uid = json.loads(requests.get('{}users/ajskateboarder/'.format(Scratch.API_URL)).text)['id']
        return '{}get_image/user/{}_60x60.png'.format(Scratch.CDN_URL, uid)
```

**Comment by The-Cloud-Dev** [comment]
I'm closing this issue since the owner did not elaborate the feature they wanted to be implemented.

**Comment by AybarsA123** [comment]
Yes

5 Şub 2022 Cmt 13:29 tarihinde TheCloudDev ***@***.***> şunu
yazdı:
