### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by Secret-chest** [The-Cloud-Dev/scratch2py#28]
Do you think my project (Scratch2Python) would get confused with your project? If you think so, I'll ask the Scratch forums for a better name for the full release.

**Comment by The-Cloud-Dev** [comment]
I think you should change it, because my original name idea was Scratch2Python, so I shortened it to Scratch2Py!
And it does sound pretty similar..

**Comment by Secret-chest** [comment]
Ok :D I have opened issue Secret-chest/Scratch2Python#23 for changing it.

**Comment by Secret-chest** [comment]
@The-Cloud-Dev You can come up with some names too. Remember, it's not going to be a library.
