### ISSUE TITLE
NameError: name 'Scratch2Py' is not defined

### ISSUE THREAD

**Issue by NiekvD** [The-Cloud-Dev/scratch2py#29]
when using the example code it gives an error
`NameError: name 'Scratch2Py' is not defined`
all packages are imported

**Comment by themysticsavages** [comment]
What all did you run? Did you run the `pip install` command?

**Comment by FuchsCrafter** [comment]
Please provide more information

**Comment by The-Cloud-Dev** [comment]
Closing as not enough information was provided
