### ISSUE TITLE
turbowarpConnect is not defined!

### ISSUE THREAD

**Issue by learn43** [The-Cloud-Dev/scratch2py#30]
Amazing work, btw, but a push for the Turbowarp, would be pretty epic!

**Comment by FuchsCrafter** [comment]
Could you please provide more pieces of information?

**Comment by learn43** [comment]
turbowarpConnect class (found in README.MD) is not present in any of the other code, therefore it is not defined. The projects works well with scratch variables but it doesn't currently work with Turbowarp.

**Comment by FuchsCrafter** [comment]
Yes, here is why: #22

**Comment by learn43** [comment]
> Yes, here is why: #22

shame, ok
