### ISSUE TITLE
Scratch2py will not install on windows or rasberry pi(raspbian)

### ISSUE THREAD

**Issue by drewban** [The-Cloud-Dev/scratch2py#32]
I dont know how to install scratch2py on my rasberry pi. I tried running the command, but It says I dont have the right version.

**Comment by FuchsCrafter** [comment]
Which Python Version do you use? (Use `python --version`)

**If (above) Version 3 of Python:**
If you try 
```bash
sudo apt-get update && sudo apt-get upgrade
```
and then 
```bash
sudo pip3 install scratch2py
``` 
and 
```bash
sudo --force-reinstall websocket-client
```
What is the output?

**Comment by The-Cloud-Dev** [comment]
Closing as not enough information was provided
