### ISSUE TITLE
How do I encode/decode in Scratch?

### ISSUE THREAD

**Issue by RixInGithub** [The-Cloud-Dev/scratch2py#36]
I use the `encode`/`decode` functions of this module. Can I replicate the same on Scratch? I've been having issues trying to replicate the encoding behavior on Scratch, and I think I'd struggle to code in the decoding too...

**EDIT**: [RENAMETOSB3.zip](https://github.com/The-Cloud-Dev/scratch2py/files/12503639/RENAMETOSB3.zip)

**Comment by The-Cloud-Dev** [comment]
You can use ScratchEncoder on Scratch to replicate the same behaviour: https://scratch.mit.edu/projects/546443308/
