### ISSUE TITLE
Unable to post comments

### ISSUE THREAD

**Issue by themysticsavages** [The-Cloud-Dev/scratch2py#8]
It looks like there is an issue with posting comments on studios. When you send a comment, it never shows up. And I think it has something to do with the response you can log.
```bash
[{"username": "", "num_tries": 0, "success": 0, "msg": "", "messages": [], "id": null}]
```
It might just be Scratch's servers since they did say they are doing a lot of backend work.

**Comment by The-Cloud-Dev** [comment]
I posted a comment about 9 hours and It seems to have appeared now.
